
export type LightingStyle = 'Natural Light' | 'Studio Light' | 'Golden Hour' | 'Blue Hour' | 'Cinematic' | 'Dramatic';
export type CameraPerspective = 'Front View' | 'Top View' | 'Side View' | '45° Angle' | 'Close-up' | 'Macro Shot';
export type AspectRatio = '1:1' | '16:9' | '9:16' | '4:3' | '3:4';

export interface CustomizationOptions {
  lightingStyle: LightingStyle;
  cameraPerspective: CameraPerspective;
}

export interface ImageFile {
  base64: string;
  mimeType: string;
  name: string;
}

export interface HistoryItem {
  image: ImageFile;
  prompt: string;
}

export interface ProjectBase {
  id: string;
  name: string;
}

export interface SceneLayer {
  id: string;
  name: string;
  nameAr: string;
  icon: string;
  category: 'hero' | 'foreground' | 'background' | 'lighting' | 'camera';
  description: string;
  descriptionEn: string;
  active: boolean;
  color: string;
  badge?: string;
}

export interface SceneAnalysisResult {
  heroSubject: string;
  referenceAnalysis: string;
  layers: SceneLayer[];
  optimizedPromptEn: string;
  arabicSummary: string;
  estimatedAtmosphere: string;
}

export interface CreatorStudioProject extends ProjectBase {
  productImages: ImageFile[];
  styleImages: ImageFile[];
  generatedImage: ImageFile | null;
  history: HistoryItem[];
  options: CustomizationOptions;
  prompt: string;
  isPromptAutoGenerated: boolean;
  styleDescription: string | null;
  isAnalyzingStyle: boolean;
  isLoading: boolean;
  error: string | null;
  uploadingTarget: 'product' | 'style' | null;
  translatedPrompt: string | null;
  isTranslating: boolean;
  editPrompt: string;
  isEditing: boolean;
  sceneAnalysis?: SceneAnalysisResult | null;
  isAnalyzingScene?: boolean;
  hyperSocialDNA?: HyperUniversalSocialDNA | null;
  isAnalyzingDNA?: boolean;
}


// --- App View ---
export type AppView = 'creator_studio' | 'photoshoot_director' | 'prompt_studio' | 'voice_over_studio' | 'campaign_studio' | 'plan_studio' | 'edit_studio' | 'storyboard_studio' | 'marketing_studio' | 'controller_studio' | 'video_flow_studio' | 'social_hub_studio' | 'community_brain_studio';

// --- Google User Auth Profile ---
export interface GoogleUserProfile {
  id: string;
  name: string;
  email: string;
  avatar: string;
  signedInAt: number;
  quotaTier: 'Personal Google AI Studio Quota' | 'Enterprise';
  quotaStatus: 'active' | 'warning' | 'exhausted';
  autoManaged: boolean;
}

// --- Social Hub & Connected Platforms ---
export type SocialPlatformId = 'instagram' | 'tiktok' | 'youtube' | 'twitter' | 'facebook' | 'linkedin' | 'pinterest' | 'threads' | 'whatsapp';

export interface SocialConnectedAccount {
  id: SocialPlatformId;
  name: string;
  icon: string;
  color: string;
  badge: string;
  isConnected: boolean;
  username: string;
  handle: string;
  avatarUrl: string;
  followers: string;
  lastConnectedAt?: number;
  autoSync: boolean;
  permissions: string[];
  aspectRatioHint: string;
  characterLimit: number;
}

export interface SocialScheduledPost {
  id: string;
  platformId: SocialPlatformId;
  caption: string;
  hashtags: string;
  scheduledTime: string;
  image?: ImageFile | null;
  videoUrl?: string | null;
  status: 'scheduled' | 'published' | 'draft';
  publishedAt?: number;
  engagement?: {
    likes: number;
    comments: number;
    shares: number;
    reach: number;
  };
}


// --- Photoshoot Director ---
export type ShotType = string;

export interface PhotoshootResult {
  shotType: ShotType;
  image: ImageFile | null;
  isLoading: boolean;
  error: string | null;
  editPrompt: string;
  isEditing: boolean;
}

export interface PhotoshootState {
  productImages: ImageFile[];
  selectedShotTypes: ShotType[];
  results: PhotoshootResult[];
  isGenerating: boolean;
  error: string | null;
  isUploading: boolean;
  customStylePrompt: string;
}

export interface PhotoshootDirectorProject extends ProjectBase, PhotoshootState {}


// --- Prompt Studio ---
export interface PromptStudioHistoryItem {
  image: ImageFile;
  instructions: string;
  generatedPrompt: string;
}

export interface PromptStudioState {
  images: ImageFile[];
  instructions: string;
  generatedPrompt: string | null;
  history: PromptStudioHistoryItem[];
  isLoading: boolean;
  isUploading: boolean;
  error: string | null;
}

export interface PromptStudioProject extends ProjectBase, PromptStudioState {}

// --- Voice Over Studio ---
export interface AudioFile {
  base64: string;
  name: string;
}

export interface VoiceOverHistoryItem {
  audio: AudioFile;
  text: string;
  voice: string;
  style: string;
}

export interface VoiceOverStudioState {
  text: string;
  styleInstructions: string;
  selectedVoice: string;
  dialect?: string;
  tone?: string;
  speed?: number;
  bgmPreset?: string;
  isRewritingScript?: boolean;
  generatedAudio: AudioFile | null;
  isLoading: boolean;
  error: string | null;
  history: VoiceOverHistoryItem[];
  isPlaying: boolean;
  voiceGenderFilter: 'All' | 'Male' | 'Female';
  previewLoadingVoice: string | null;
  previewPlayingVoice: string | null;
}

export interface MasterPromptSuggestion {
  title: string;
  category: string;
  prompt: string;
  arabicHeadlineHook?: string;
  visualHook?: string;
  tags: string[];
}


export interface VoiceOverStudioProject extends ProjectBase, VoiceOverStudioState {}

// --- Branding Studio ---
export type BrandingResultCategory = 'Logo Construction Grid' | 'Typography Showcase' | 'Logo Color Variations' | 'Monochrome Version' |
    '3D Glass Logo' | 'Business Card Mockup' | '3D Glass App Icon' | 'Creative Pen Mockup' |
    'Merchandise (Tote Bag)' | 'Pencil Sketch Logo' | 'Notebook Mockup' | 'Waving Flag Mockup';

export interface BrandingResult {
  category: BrandingResultCategory;
  image: ImageFile | null;
  isLoading: boolean;
  isEditing: boolean;
  error: string | null;
  editPrompt: string;
}

export interface BrandingStudioState {
  logos: ImageFile[];
  isUploading: boolean;
  error: string | null;
  results: BrandingResult[];
  colors: string[];
  isAnalyzing: boolean;
  isGenerating: boolean;
  aspectRatio: AspectRatio;
}

export interface BrandingStudioProject extends ProjectBase, BrandingStudioState {}

// --- Campaign Studio ---
export type CampaignScenario = string;

export interface CampaignResult {
    scenario: CampaignScenario;
    image: ImageFile | null;
    isLoading: boolean;
    error: string | null;
    editPrompt: string;
    isEditing: boolean;
}

export interface CampaignStudioState {
    productImages: ImageFile[];
    isUploading: boolean;
    isAnalyzing: boolean;
    isGenerating: boolean;
    error: string | null;
    results: CampaignResult[];
    productAnalysis: string | null;
    selectedMood: string;
    customPrompt: string;
    mode: 'auto' | 'custom';
    customIdeas: string[];
}

export interface CampaignStudioProject extends ProjectBase, CampaignStudioState {}

// --- Plan Studio ---
export interface PlanIdea {
    id: string;
    scenario: string;
    caption: string;
    tov: string;
    schedule: string;
    image: ImageFile | null;
    isLoadingImage: boolean;
    imageError: string | null;
}

export interface PlanStudioState {
    productImages: ImageFile[];
    logos: ImageFile[];
    prompt: string;
    targetMarket: string;
    dialect: string;
    categoryAnalysis: string | null;
    isAnalyzingCategory: boolean;
    ideas: PlanIdea[];
    isGeneratingPlan: boolean;
    isUploading: boolean;
    error: string | null;
}

export interface PlanStudioProject extends ProjectBase, PlanStudioState {}

// --- Storyboard Studio ---
export interface StoryboardScene {
    id: string;
    sequence: number;
    description: string;
    cameraAngle: string;
    visualPrompt: string;
    image: ImageFile | null;
    isLoading: boolean;
    error: string | null;
}

export interface StoryboardStudioState {
    subjectImages: ImageFile[];
    customInstructions: string;
    aspectRatio: AspectRatio;
    scenes: StoryboardScene[];
    gridImage: ImageFile | null;
    isGeneratingPlan: boolean;
    isGeneratingGrid: boolean;
    isUploading: boolean;
    error: string | null;
}

export interface StoryboardStudioProject extends ProjectBase, StoryboardStudioState {}

// --- Marketing Studio ---
export interface MarketingAdCreative {
    id: string;
    headline: string;
    platform: string;
    aspectRatio: AspectRatio;
    visualScenario: string;
    imagePrompt: string;
    caption: string;
    cta: string;
    generatedImage?: ImageFile | null;
    isGeneratingImage?: boolean;
    imageError?: string | null;
}

export interface IntegratedCampaignData {
    bigIdea: string;
    slogan: string;
    usp: string;
    executiveSummary: string;
    persona: {
        name: string;
        demographics: string;
        painPoints: string[];
        desires: string[];
        psychologicalTrigger: string;
    };
    creatives: MarketingAdCreative[];
    shortFormVideoScript: {
        hook: string;
        body: string;
        cta: string;
        visualNotes: string;
    };
    voiceoverScript: {
        text: string;
        tone: string;
        suggestedDuration: string;
    };
    budgetAndChannels: {
        budgetAllocation: { channel: string; percentage: number; rationale: string }[];
        launchRoadmap: { phase: string; duration: string; action: string }[];
        targetKpis: string[];
    };
    swot: {
        strengths: string[];
        weaknesses: string[];
        opportunities: string[];
        threats: string[];
    };
}

export interface MarketingStudioState {
    brandType: 'new' | 'existing';
    entityType: 'product' | 'service' | 'store_app';
    campaignGoal: 'sales' | 'awareness' | 'leads' | 'launch' | 'promo';
    brandName: string;
    specialty: string;
    brief: string;
    websiteLink: string;
    targetMarket: string;
    selectedPlatforms: string[];
    dialect: string;
    language: 'ar' | 'en';
    logoImages: ImageFile[];
    productImages: ImageFile[];
    isUploadingLogo?: boolean;
    isUploadingProduct?: boolean;
    result: string | null;
    campaignData: IntegratedCampaignData | null;
    isGenerating: boolean;
    error: string | null;
    hyperSocialDNA?: HyperUniversalSocialDNA | null;
    isAnalyzingDNA?: boolean;
}

export interface MarketingStudioProject extends ProjectBase, MarketingStudioState {}

// --- Edit Studio (PRO UPDATED) ---
export interface LocalText {
    id: string; 
    content: string;
    fontSize: number;
    color: string;
    fontFamily: string;
    fontWeight: string;
    x: number;
    y: number;
    isVisible: boolean;
    rotation: number;
    letterSpacing: number;
    lineHeight: number;
    maxWidth: number; // New: Controls wrapping/lines (Percentage of container width)
}

export interface GlobalLayer {
    id: string;
    file: ImageFile;
    scale: number;
    x: number;
    y: number;
}

export interface EditAdjustments {
    sharpness: number;
    lut: string; 
}

// Added EditStudioState to define missing state properties for EditStudioProject
export interface EditStudioState {
    baseImages: ImageFile[];
    localTexts: { [key: number]: LocalText[] };
    committedTexts: { [key: number]: LocalText[] };
    globalLayers: GlobalLayer[];
    adjustments: EditAdjustments;
    isUploading: boolean;
    error: string | null;
}

export interface EditStudioProject extends ProjectBase, EditStudioState {}

// --- Controller Studio ---
// Fix: Added missing types for Controller Studio
export type ControlCategory = 'Face' | 'Head' | 'Body' | 'Retouch';

export interface ControllerSlider {
    id: string;
    label: string;
    value: number;
    min: number;
    max: number;
    step: number;
    category: ControlCategory;
}

export interface ControllerStudioProject extends ProjectBase {
    sourceImages: ImageFile[];
    generatedImage: ImageFile | null;
    sliders: ControllerSlider[];
    activeCategory: ControlCategory;
    isGenerating: boolean;
    isUploading: boolean;
    error: string | null;
    history: HistoryItem[];
}

export interface ImpossibleHandoffTimelineSegment {
  time: string;
  action: string;
  camera: string;
  dialogue?: string;
  visual?: string;
  transition?: string;
  physicalResponse?: string;
  important?: string;
}

export interface ImpossibleHandoffBlueprint {
  series: number;
  scene: number;
  title: string;
  duration: string;
  format: string;
  resolution: string;
  fps: number;
  coreHookMechanic: {
    name: string;
    formula: string;
    lesson: string;
  };
  continuity: {
    startingFrame: string;
    sameHero: boolean;
    sameIdentity: boolean;
    sameWardrobe: boolean;
    sameEnvironment: boolean;
    sameLogo: boolean;
    noReset: boolean;
  };
  brandLock: {
    brand: string;
    logoInstruction: string;
    usage: string;
    geometry: string;
    proportions: string;
    colors: string;
    noRedesign: boolean;
    noMorphing: boolean;
    noFlatOverlay: boolean;
  };
  characterLock: {
    identity: string;
    wardrobe: string;
    face: string;
    noFaceMorphing: boolean;
    noWardrobeChange: boolean;
  };
  openingFrame: {
    description: string;
    camera: string;
    action: string;
    dialogue: string;
  };
  timeline: ImpossibleHandoffTimelineSegment[];
  transitionEngine: {
    primaryTransition: string;
    object: string;
    rule: string;
    cameraLogic: string;
    newEnvironment: string;
    noCut: boolean;
    noMorph: boolean;
    noTeleport: boolean;
  };
  cameraDirection: {
    opening: string;
    handoff: string;
    occlusion: string;
    transition: string;
    reveal: string;
    ending: string;
    style: string;
    allMotionPhysicallyMotivated: boolean;
  };
  soundDesign: {
    opening: string;
    objectPickup: string;
    throwSound: string;
    lensOcclusion: string;
    newRoom: string;
    activation: string;
    music: string;
    voice: string;
    lipSync: string;
    noSubtitles: boolean;
  };
  performanceDirection: {
    hero: string;
    throwAction: string;
    catchAction: string;
    transition: string;
    ending: string;
    noOveracting: boolean;
    noComedicExpression: boolean;
  };
  environmentDesign: {
    firstEnvironment: string;
    secondEnvironment: string;
    secondRoom: string;
    brandIntegration: string;
    noRandomText: boolean;
    noFakeUiText: boolean;
  };
  visualQuality: {
    style: string;
    lens: string;
    motionBlur: string;
    depthOfField: string;
    reflections: string;
    lighting: string;
    particles: string;
    noVisualNoise: boolean;
  };
  hardConstraints: {
    singleHero: boolean;
    singleSmallEmblem: boolean;
    singleMainLogo: boolean;
    sameEmblemEntireScene: boolean;
    sameHeroIdentity: boolean;
    sameWardrobe: boolean;
    noExtraPeople: boolean;
    noExtraHands: boolean;
    noDeformedLimbs: boolean;
    noFaceMorphing: boolean;
    noBackgroundMutation: boolean;
    noObjectTeleportation: boolean;
    noObjectDuplication: boolean;
    noLogoMorphing: boolean;
    noLogoDistortion: boolean;
    noRandomExplosions: boolean;
    noWeapons: boolean;
    noSubtitles: boolean;
    noWatermark: boolean;
    noGeneratedText: boolean;
    noUnmotivatedCuts: boolean;
    realisticPhysics: boolean;
    perfectLipSync: boolean;
  };
  hookPrinciple: {
    core: string;
    creatorTakeaway: string;
    seriesTakeaway: string;
  };
  finalFrame: {
    description: string;
    camera: string;
    hero: string;
    smallEmblem: string;
    largeLogo: string;
    lighting: string;
    motion: string;
    mustBeUsedAsExactStartingFrameForNextSeries: boolean;
  };
}

export interface DirectorialPromptLayers {
  hookUpAr: string;
  hookUpEn: string;
  hookType: 'sensory_shock' | 'mystery_reveal' | 'problem_solution' | 'luxury_prestige' | 'speed_energy';
  cameraLayerEn: string;
  cameraLayerAr: string;
  lightingLayerEn: string;
  lightingLayerAr: string;
  productMotionLayerEn: string;
  productMotionLayerAr: string;
  climaxLayerEn: string;
  climaxLayerAr: string;
  fullPromptEn: string;
  geniusSceneStoryAr: string;
  soundEffectsAr?: string;
  // Comedic Sales Video Directorial Additions
  dialect?: 'سعودي معاصر' | 'مصري حماسي' | 'خليجي فخم' | 'شامي مرح' | 'عالمي فصحى';
  lipSyncScriptAr?: string;
  lipSyncScriptEn?: string;
  sellingGesturesAr?: string[];
  sellingGesturesEn?: string;
  comedyVibe?: string;
  viralCallToActionAr?: string;
}

export interface VideoFlowState {
  prompt: string;
  sourceImage: ImageFile | null;
  cameraMotion: 'pan_right' | 'pan_left' | 'zoom_in' | 'zoom_out' | 'orbit_360' | 'dynamic_dolly' | 'crane_shot' | 'static_lock' | 'impossible_handoff';
  motionDynamics: 'smooth_commercial' | 'viral_energetic' | 'slow_motion';
  aspectRatio: '9:16' | '16:9' | '1:1';
  resolution: '720p' | '1080p';
  durationSeconds: number;
  isGenerating: boolean;
  generatedVideoUrl: string | null;
  generatedVideoBase64?: string | null;
  progressStage: string | null;
  error: string | null;
  voiceoverAudio?: AudioFile | null;
  sourceStudio?: string | null;
  directorialLayers?: DirectorialPromptLayers | null;
  hyperSocialDNA?: HyperUniversalSocialDNA | null;
  impossibleHandoffBlueprint?: ImpossibleHandoffBlueprint | null;
}

export interface VideoFlowProject extends ProjectBase, VideoFlowState {}

// --- HYPER UNIVERSAL SOCIAL ENGINE V1.0 DATA STRUCTURES ---
export interface ColorConstitution {
  primary: string; // Hex color extracted from logo/reference
  primaryName: string;
  secondary: string;
  secondaryName: string;
  neutral: string;
  neutralName: string;
  cinematicGradingRules: string;
}

export interface FaceLockProfile {
  detected: boolean;
  lockedId: string;
  gender: string;
  estimatedAge: string;
  facialStructure: string;
  hairStyleAndColor: string;
  eyeColorAndExpression: string;
  skinToneHex: string;
  characterEnergy: string;
  bodyType: string;
  persistentLockPromptEn: string;
}

export interface CharacterEngineProfile {
  characterArchetype: string;
  comedyStyle: string;
  facialExpressions: string[];
  exaggeratedPoses: string[];
  oversizedHandsInteraction: string;
  impossibleActionPromptEn: string;
}

export interface ComedicSalesVideoDirection {
  dialect: 'سعودي معاصر' | 'مصري حماسي' | 'خليجي فخم' | 'شامي مرح' | 'عالمي فصحى';
  comedyVibe: string;
  lipSyncScriptAr: string;
  lipSyncScriptEn: string;
  sellingGesturesAr: string[]; // حركات تبيع: شاور على السعر مع صدمة، لقطة سقوط فك، رقصة فوز مجنونة
  sellingGesturesEn: string;
  viralCallToActionAr: string;
  sceneDirectorialPromptEn: string;
}

export interface HyperUniversalSocialDNA {
  id: string;
  analyzedAt: number;
  referenceSource: string;
  // Layer 01: Universal Brand AI
  brandAI: {
    businessActivity: string;
    industry: string;
    brandPersonality: string;
    brandEmotion: string;
    marketingObjective: string;
    targetAudience: string;
    productType: string;
  };
  // Layer 02: Color Constitution (Strictly max 3 colors)
  colorConstitution: ColorConstitution;
  // Layer 03: Face Lock AI
  faceLock: FaceLockProfile;
  // Layer 04: Character Engine
  characterEngine: CharacterEngineProfile;
  // Layer 05: Scroll Stop Engine
  scrollStopVerdict: {
    stopsUnderOneSecond: boolean;
    curiosityFactor: number;
    stopScrollHookAr: string;
  };
  // Layer 06: Visual Story AI
  visualStory: {
    beginning: string;
    curiosity: string;
    emotion: string;
    solution: string;
    brandLock: string;
  };
  // Layer 07: Smart Camera
  smartCamera: string;
  // Layer 08: Depth Engine (8 Layers)
  depthEngine: {
    layer01ForegroundFX: string;
    layer02ForegroundObjects: string;
    layer03HeroCharacter: string;
    layer04Product: string;
    layer05InteractiveObjects: string;
    layer06Environment: string;
    layer07Background: string;
    layer08Atmosphere: string;
  };
  // Layer 09: Smart Environment
  smartEnvironment: string;
  // Layer 10: Visual Hook AI
  visualHook: {
    type: 'Oversized Object' | 'Funny Character' | 'Impossible Scale' | 'Portal' | 'Floating Product' | 'Flying Objects' | 'Mini World' | 'Giant Hand' | 'Breaking Reality' | 'Gravity Defying';
    descriptionAr: string;
    promptEn: string;
  };
  // Layer 11: Typography AI
  typographyAI: {
    fontStyle: string;
    interactionWithHero: string;
    arabic3DStylingPromptEn: string;
  };
  // Layer 12: Smart Headline AI
  smartHeadlineAI: {
    viralHookHeadlineAr: string; // 2-5 words max
    subheadAr?: string;
  };
  // Layer 13: Composition Engine
  composition: {
    gridRule: string;
    eyeTrackingFocalPoint: string;
  };
  // Layer 14: Industry Engine
  industryCategory: string;
  // Layer 15: No Repetition AI Key
  uniqueSignatureKey: string;
  // Master Synthesized Prompts
  masterUniversalPromptEn: string;
  // Video Direction: Comedic Dialect Sales Director
  comedicSalesVideo: ComedicSalesVideoDirection;
}

// --- Persistent User Studio Works (محفظة استوديو الأعمال لكل مستخدم) ---
export interface StudioWorkItem {
  id: string;
  createdAt: number;
  title: string;
  prompt: string;
  studioType: 'creator_studio' | 'photoshoot' | 'marketing' | 'storyboard' | 'voiceover' | 'edit' | 'video_flow';
  image?: ImageFile;
  audio?: AudioFile;
  videoUrl?: string;
  aspectRatio?: string;
  isFavorite?: boolean;
  layersCount?: number;
  metadata?: {
    atmosphere?: string;
    styleDescription?: string;
    shotType?: string;
    campaignTitle?: string;
    cameraMotion?: string;
    sceneAnalysis?: SceneAnalysisResult;
    hyperSocialDNA?: HyperUniversalSocialDNA;
    thinkingRationale?: ThinkingRationale;
  };
}

// --- COMMUNITY PROMPT & THINKING BRAIN (العقل التشاركي وتغذية المنصة وسلسلة التفكير) ---
export interface ThinkingRationale {
  audiencePainPointAr: string;        // نقطة الألم النفسية للجمهور المستهدف
  scrollStopStrategyAr: string;       // خطة كسر التمرير (Scroll Stop) في أقل من ثانية
  dnaRulesSummaryAr: string;          // دستور الألوان والـ DNA البصري المطبق
  lipSyncAndGesturesAr?: string;      // سر نجاح حركة الشفاه وحركات البيع
  promptArchitectureEn: string;       // تفكيك بنية البرومبت الإخراجي
  estimatedConversionRate?: string;   // التوقع البيعي ونسبة التحويل
  reasoningStepsAr: string[];         // خطوات التفكير التسلسلية للمخرج الإعلاني
}

export interface CommunityThoughtItem {
  id: string;
  authorName: string;
  authorAvatar?: string;
  industry: string;
  title: string;
  prompt: string;
  thinking: ThinkingRationale;
  image?: ImageFile;
  videoUrl?: string;
  promptPowerScore: number;           // مقياس قوة البرومبت من 100
  scrollStopRating: number;           // معدل كسر التمرير من 100
  likesCount: number;
  remixCount: number;
  dialect?: string;
  createdAt: number;
  tags: string[];
  isFeatured?: boolean;
}

