
import React, { useEffect, useRef, useCallback, useState } from 'react';
import { CreatorStudioProject, ImageFile, HyperUniversalSocialDNA } from '../types';
import { analyzeStyleImage, translateText, generateImage, editImage, analyzeSceneLayers, analyzeHyperUniversalSocialDNA } from '../services/geminiService';
import { validateQuotaUsage } from '../services/quotaGuard';
import { saveStudioWork } from '../services/studioStorageService';
import { resizeImage } from '../utils';
import CustomizationPanel from './CustomizationPanel';
import ImageWorkspace from './ImageWorkspace';
import PromptEditor from './PromptEditor';
import HistoryPanel from './HistoryPanel';
import ResultDisplay from './ResultDisplay';
import SceneLayerBuilder from './SceneLayerBuilder';
import VisualDNAInspectorModal from './VisualDNAInspectorModal';

interface CreatorStudioProps {
  project: CreatorStudioProject;
  setProject: React.Dispatch<React.SetStateAction<CreatorStudioProject>>;
  onOpenSocialEngine?: (work?: any, image?: ImageFile | null, prompt?: string) => void;
  onRequestVideo?: (image: ImageFile | null, prompt: string, dna?: HyperUniversalSocialDNA | null) => void;
}

const CreatorStudio: React.FC<CreatorStudioProps> = ({
  project,
  setProject,
  onOpenSocialEngine,
  onRequestVideo,
}) => {
  const [isDNAModalOpen, setIsDNAModalOpen] = useState(false);
  const translateTimeoutRef = useRef<number | null>(null);
  const translationRequestCounter = useRef(0);
  const lastAnalyzedRefsKey = useRef<string>('');

  const updateActiveProjectState = useCallback((updater: (projectDraft: CreatorStudioProject) => void) => {
    setProject(currentProject => {
      const projectToUpdate = { ...currentProject };
      updater(projectToUpdate);
      return projectToUpdate;
    });
  }, [setProject]);

  // Analyze reference images & HYPER UNIVERSAL SOCIAL ENGINE DNA automatically whenever ANY reference is uploaded
  useEffect(() => {
    if (!project) return;
    const allRefs = [...(project.styleImages || []), ...(project.productImages || [])];
    const currentRefsKey = allRefs.map(img => img.name || img.base64.slice(0, 24)).join('|');

    // Trigger analysis if references exist and haven't been analyzed yet
    if (allRefs.length > 0 && currentRefsKey !== lastAnalyzedRefsKey.current && !project.isAnalyzingDNA) {
      lastAnalyzedRefsKey.current = currentRefsKey;

      const triggerFullReferenceAnalysis = async () => {
        updateActiveProjectState(p => { 
          p.isAnalyzingDNA = true;
          if (p.styleImages?.length > 0 && !p.styleDescription) {
            p.isAnalyzingStyle = true;
          }
          p.error = null;
        });

        try {
          const promises: [Promise<HyperUniversalSocialDNA>, Promise<string | null>] = [
            analyzeHyperUniversalSocialDNA(allRefs, project.prompt, 'سعودي معاصر'),
            project.styleImages?.length > 0 && !project.styleDescription 
              ? analyzeStyleImage(project.styleImages) 
              : Promise.resolve(project.styleDescription || null)
          ];

          const [dnaResult, styleDesc] = await Promise.all(promises);

          updateActiveProjectState(p => { 
            p.hyperSocialDNA = dnaResult;
            if (styleDesc) p.styleDescription = styleDesc;
            // If prompt is empty or auto-generated, initialize with the Master Universal DNA prompt
            if (!p.prompt || p.isPromptAutoGenerated) {
              p.prompt = dnaResult.masterUniversalPromptEn;
              p.isPromptAutoGenerated = false;
            }
          });
        } catch (err) {
          console.error(err);
          updateActiveProjectState(p => {
            p.error = err instanceof Error ? err.message : "تعذر استخراج الـ DNA الإعلاني الموحد للمراجع.";
          });
        } finally {
          updateActiveProjectState(p => { 
            p.isAnalyzingStyle = false;
            p.isAnalyzingDNA = false;
          });
        }
      };

      triggerFullReferenceAnalysis();
    } else if (allRefs.length === 0 && (project.hyperSocialDNA || project.styleDescription)) {
      lastAnalyzedRefsKey.current = '';
    }
  }, [
    project?.id,
    project?.productImages,
    project?.styleImages, 
    project?.styleDescription,
    project?.hyperSocialDNA,
    project?.isAnalyzingDNA,
    project?.prompt,
    project?.isPromptAutoGenerated,
    updateActiveProjectState
  ]);

  // Auto-generate prompt - MODIFIED: only fills if empty and auto-mode is ON
  useEffect(() => {
    if (!project || !project.isPromptAutoGenerated) return;
    
    const { productImages, styleImages, options, isAnalyzingStyle, styleDescription } = project;
    
    if (productImages.length === 0 && styleImages.length === 0) {
      return;
    }

    let newPrompt = `Professional high-end commercial photograph`;
    if (productImages.length > 0) {
      newPrompt += ` of the subject from the provided image`;
    }
    
    newPrompt += `. 

Setting: Place the subject in a sophisticated and professional new environment that captures the essence, mood, and background aesthetic of the style reference. The background should be a high-quality reimagining inspired by the style reference, ensuring it complements the subject perfectly.

Key requirements:
- Lighting: ${options.lightingStyle} with professional studio quality.
- Perspective: ${options.cameraPerspective}.
- Mood: High-end, clean, and professional.
- Content Protection: STRICTLY PRESERVE all original text, labels, and branding on the product. DO NOT erase or modify existing writing. NO EXTRA generated text in the scene. 8k resolution, sharp focus, hyper-realistic.`;

    if (styleImages.length > 0) {
      if (isAnalyzingStyle) newPrompt += `\n- Visual Inspiration: Reimagining the reference style...`;
      else if (styleDescription) newPrompt += `\n- Background/Style Essence: ${styleDescription}. Create a similar professional atmosphere.`;
      else newPrompt += `\n- Background/Style Essence: Resembling the provided style reference atmosphere and lighting.`;
    }
    
    if(project.prompt === '') updateActiveProjectState(p => { p.prompt = newPrompt; });
  }, [
    project?.id,
    project?.isPromptAutoGenerated,
    project?.productImages, 
    project?.styleImages, 
    project?.options, 
    project?.isAnalyzingStyle, 
    project?.styleDescription,
    updateActiveProjectState
  ]);

  // Translation effect
  useEffect(() => {
    const arabicRegex = /[\u0600-\u06FF]/;
    if (!project || project.isPromptAutoGenerated) {
        if (project?.translatedPrompt || project?.isTranslating) {
            updateActiveProjectState(p => { p.translatedPrompt = null; p.isTranslating = false; });
        }
        return;
    }

    if (translateTimeoutRef.current) clearTimeout(translateTimeoutRef.current);
    const promptToTranslate = project.prompt;

    if (!arabicRegex.test(promptToTranslate) || !promptToTranslate.trim()) {
        if (project.translatedPrompt || project.isTranslating) {
            updateActiveProjectState(p => { p.translatedPrompt = null; p.isTranslating = false; });
        }
        return;
    }

    translateTimeoutRef.current = window.setTimeout(async () => {
        translationRequestCounter.current += 1;
        const currentRequestId = translationRequestCounter.current;
        updateActiveProjectState(p => { p.isTranslating = true; p.error = null; });

        try {
            const translated = await translateText(promptToTranslate);
            if (translationRequestCounter.current === currentRequestId) {
                updateActiveProjectState(p => { if (p.prompt === promptToTranslate) p.translatedPrompt = translated; });
            }
        } catch (err) {
            console.error(err);
            if (translationRequestCounter.current === currentRequestId) {
                updateActiveProjectState(p => { p.error = err instanceof Error ? err.message : 'Translation failed.'; });
            }
        } finally {
            if (translationRequestCounter.current === currentRequestId) {
                updateActiveProjectState(p => { p.isTranslating = false; });
            }
        }
    }, 1200);
  }, [project?.prompt, project?.isPromptAutoGenerated, updateActiveProjectState]);

  const handleAnalyzeScene = useCallback(async (customPrompt?: string) => {
    if (!project) return;
    const promptToAnalyze = customPrompt || project.prompt;
    if (!promptToAnalyze || !promptToAnalyze.trim()) {
      updateActiveProjectState(p => { p.error = 'يرجى إدخال أمر أو وصف للمشهد للبدء في تحليل الطبقات.'; });
      return;
    }

    updateActiveProjectState(p => { p.isAnalyzingScene = true; p.error = null; });
    try {
      const result = await analyzeSceneLayers(promptToAnalyze, project.productImages, project.styleImages);
      updateActiveProjectState(p => {
        p.sceneAnalysis = result;
        p.isAnalyzingScene = false;
      });
    } catch (err) {
      console.error(err);
      updateActiveProjectState(p => {
        p.isAnalyzingScene = false;
        p.error = err instanceof Error ? err.message : 'فشل تحليل معمارية المشهد';
      });
    }
  }, [project, updateActiveProjectState]);

  const handleAnalyzeDNA = useCallback(async (dialect: 'سعودي معاصر' | 'مصري حماسي' | 'خليجي فخم' | 'شامي مرح' | 'عالمي فصحى' = 'سعودي معاصر') => {
    if (!project) return;
    const refs = [...project.styleImages, ...project.productImages];
    if (refs.length === 0 && !project.prompt.trim()) {
      updateActiveProjectState(p => { p.error = 'يرجى رفع صورة مرجعية أو كتابة وصف النشاط لاستخراج الـ DNA البصري.'; });
      return;
    }

    updateActiveProjectState(p => { p.isAnalyzingDNA = true; p.error = null; });
    try {
      const dna = await analyzeHyperUniversalSocialDNA(refs, project.prompt, dialect);
      updateActiveProjectState(p => {
        p.hyperSocialDNA = dna;
        p.isAnalyzingDNA = false;
      });
      setIsDNAModalOpen(true);
    } catch (err) {
      console.error(err);
      updateActiveProjectState(p => {
        p.isAnalyzingDNA = false;
        p.error = 'تعذر استخراج الـ DNA الإعلاني الموحد';
      });
    }
  }, [project, updateActiveProjectState]);

  const handleApplyDNA = useCallback((dna: HyperUniversalSocialDNA) => {
    if (!project) return;
    updateActiveProjectState(p => {
      p.hyperSocialDNA = dna;
      p.prompt = dna.masterUniversalPromptEn;
      p.isPromptAutoGenerated = false;
    });
  }, [project, updateActiveProjectState]);
  
  const handleGenerate = useCallback(async (promptOverride?: string) => {
    if (!project || (!project.prompt && !promptOverride)) {
      updateActiveProjectState(p => { p.error = 'يرجى إدخال وصف أو تحديد نمط للتصميم.'; });
      return;
    }
    const currentPrompt = (promptOverride || project.prompt).trim();

    const val = validateQuotaUsage({
      studio: 'creator_studio',
      prompt: currentPrompt,
      hasRequiredMedia: project.productImages.length > 0,
      fingerprint: `creator_${currentPrompt}_${project.productImages.length}_${project.options.lightingStyle}`
    });
    if (!val.allowed) {
      updateActiveProjectState(p => { p.error = val.reason || 'حماية الكوتة نشطة لمنع الاستهلاك العبثي.'; });
      return;
    }

    updateActiveProjectState(p => { p.isLoading = true; p.error = null; p.generatedImage = null; });

    let finalPrompt = currentPrompt;
    if (project.hyperSocialDNA) {
      const dna = project.hyperSocialDNA;
      if (!finalPrompt.includes('HYPER UNIVERSAL SOCIAL ENGINE')) {
        const dnaDirectives = [
          `HYPER UNIVERSAL SOCIAL ENGINE V1.0 RULES:`,
          `Color Constitution: Strictly restrict to max 3 colors (${dna.colorConstitution.primary}, ${dna.colorConstitution.secondary}, ${dna.colorConstitution.neutral}). Identical cinematic color grading, white balance, contrast and glow.`,
          dna.faceLock.detected ? `Face Lock: Strictly lock facial identity, eye structure, hair, and skin tone (${dna.faceLock.facialStructure}, ${dna.faceLock.skinToneHex}).` : '',
          `Character & Action: ${dna.characterEngine.characterArchetype}. Highly expressive, magnetic poses, impossible interaction (${dna.characterEngine.impossibleActionPromptEn || ''}).`,
          `Scroll Stop Visual Hook: ${dna.visualHook.type} - ${dna.visualHook.promptEn}. Must stop scrolling in under 1 second.`,
          `Typography AI: ${dna.typographyAI.arabic3DStylingPromptEn}. Interacting with the hero and scene.`,
          `Depth & Atmosphere: ${dna.depthEngine.layer08Atmosphere}. Commercial photography quality, luxury finish, hyper-realistic, award-winning art direction, zero AI look.`
        ].filter(Boolean).join('\n');
        finalPrompt = `${finalPrompt}\n\n${dnaDirectives}`;
      }
    }

    try {
      const result = await generateImage(project.productImages, finalPrompt, project.styleImages);
      updateActiveProjectState(p => {
          p.generatedImage = result;
          p.history = [{ image: result, prompt: finalPrompt }, ...p.history];
      });

      // Persistent auto-save to user's Studio Works Portfolio (استوديو أعمالي)
      saveStudioWork({
        title: currentPrompt.slice(0, 45),
        prompt: finalPrompt,
        studioType: 'creator_studio',
        image: result,
        metadata: {
          atmosphere: project.sceneAnalysis?.estimatedAtmosphere || project.options.lightingStyle,
          styleDescription: project.styleDescription || undefined,
          sceneAnalysis: project.sceneAnalysis || undefined,
          hyperSocialDNA: project.hyperSocialDNA || undefined
        }
      });
    } catch (err) {
      console.error(err);
      updateActiveProjectState(p => { p.error = err instanceof Error ? err.message : 'Generation failed.'; });
    } finally {
      updateActiveProjectState(p => { p.isLoading = false; });
    }
  }, [project, updateActiveProjectState]);

  const handleLaunchLiveCampaignDemo = useCallback(async () => {
    const livePrompt = 'تصميم إعلاني سينمائي لزجاجة عطر ملكي فاخر من العود الأسود والمسك، على قاعدة من الرخام الأسود مع انعكاسات ضوئية ذهبية ناعمة وإضاءة استوديو دراماتيكية مع بخار بخور انسيابي وعمق ميدان 8K';
    updateActiveProjectState(p => {
      p.prompt = livePrompt;
      p.isPromptAutoGenerated = false;
      p.isAnalyzingScene = true;
      p.error = null;
    });

    try {
      const analysis = await analyzeSceneLayers(livePrompt, project.productImages, project.styleImages);
      updateActiveProjectState(p => {
        p.sceneAnalysis = analysis;
        p.isAnalyzingScene = false;
      });
      // Automatically generate the live campaign scene with synthesized prompt!
      handleGenerate(analysis.optimizedPromptEn);
    } catch (err) {
      console.error(err);
      updateActiveProjectState(p => {
        p.isAnalyzingScene = false;
        p.error = 'تعذر تشغيل الحملة الحية، يرجى المحاولة ثانية';
      });
    }
  }, [project, updateActiveProjectState, handleGenerate]);

  // Logic for Step 1: APPLY STOCK BASE
  const handleApplyStockBase = useCallback(() => {
    if (!project) return;
    const current = project.prompt.trim();
    const baseText = current && !current.includes("Stock photo") ? current : "the product";
    
    const updatedPrompt = `Stock photo of ${baseText}, pure white background, professional commercial photography, high-end studio lighting, sophisticated white rim lighting accents, 8k resolution, sharp focus, hyper-realistic, extremely high detail. STRICTLY PRESERVE original branding. NO EXTRA generated text.`;
    
    updateActiveProjectState(p => { 
        p.prompt = updatedPrompt; 
        p.isPromptAutoGenerated = false;
    });
  }, [project, updateActiveProjectState]);

  // NEW: Handle AI Vision Modes
  const handleApplyVisionMode = useCallback((mode: 'fusion' | 'placement') => {
    if (!project) return;
    const { styleDescription } = project;
    
    let updatedPrompt = '';
    const textConstraint = "STRICTLY PRESERVE all original text, labels, and branding. DO NOT modify existing writing. NO EXTRA generated text in the scene.";

    if (mode === 'fusion') {
        updatedPrompt = `Professional Style Fusion: Take the subject from the main image and seamlessly re-render it using the visual style, professional lighting, and artistic mood of the reference image. ${styleDescription ? `Reference context: ${styleDescription}.` : ''} High-end commercial quality, 8k resolution, photorealistic. ${textConstraint}`;
    } else {
        updatedPrompt = `Professional Scene Placement: Extract the subject from the main image and place it professionally into the exact environment, background, and spatial context of the reference image. ${styleDescription ? `Reference context: ${styleDescription}.` : ''} Match the lighting, shadows, and perspective of the reference perfectly for a hyper-realistic result. ${textConstraint}`;
    }
    
    updateActiveProjectState(p => { 
        p.prompt = updatedPrompt; 
        p.isPromptAutoGenerated = false;
    });
  }, [project, updateActiveProjectState]);

  // Logic for Step 2: CHANGE RIM COLOR
  const handleApplyRimColor = useCallback((color: string) => {
    if (!project) return;
    const current = project.prompt;
    
    if (current.includes("rim lighting")) {
        const regex = /(\w+)\s+rim lighting/;
        const updated = current.replace(regex, `${color} rim lighting`);
        updateActiveProjectState(p => { p.prompt = updated; });
    } else {
        updateActiveProjectState(p => { p.prompt = `${current} with ${color} rim lighting accents.`; });
    }
  }, [project, updateActiveProjectState]);

  const handleImageEdit = async (editPromptText: string) => {
    if (!project.generatedImage) return;
    
    updateActiveProjectState(p => { p.isEditing = true; p.error = null; });
    try {
        const result = await editImage(project.generatedImage as ImageFile, editPromptText);
        updateActiveProjectState(p => {
            p.generatedImage = result;
            p.history = [{ image: result, prompt: editPromptText }, ...p.history];
        });

        // Persist edited work to user's Studio Works Portfolio
        saveStudioWork({
          title: `تعديل: ${editPromptText.slice(0, 35)}`,
          prompt: editPromptText,
          studioType: 'edit',
          image: result,
        });
    } catch (err) {
        updateActiveProjectState(p => { p.error = err instanceof Error ? err.message : 'Edit failed'; });
    } finally {
        updateActiveProjectState(p => { p.isEditing = false; });
    }
  };


  const handleFileUpload = (updater: (files: ImageFile[]) => void, target: 'product' | 'style') => async (files: File[]) => {
      if (!files || files.length === 0) return;
      updateActiveProjectState(p => { p.uploadingTarget = target; p.error = null; });
      let currentError: string | null = null;
      
      const filePromises = files.map(file => {
          return new Promise<ImageFile | null>(async (resolve) => {
              if (!file.type.startsWith('image/')) {
                  if(!currentError) currentError = `File '${file.name}' not supported.`;
                  resolve(null); return;
              }
              try {
                  const resizedFile = await resizeImage(file, 1280, 1280, 0.85);
                  const reader = new FileReader();
                  reader.onloadend = () => {
                      resolve({ base64: (reader.result as string).split(',')[1], mimeType: resizedFile.type, name: resizedFile.name });
                  };
                  reader.readAsDataURL(resizedFile);
              } catch (err) {
                  resolve(null);
              }
          });
      });

      const results = await Promise.all(filePromises);
      const validImages = results.filter((img): img is ImageFile => img !== null);
      if (validImages.length > 0) updater(validImages);
      updateActiveProjectState(p => { p.error = currentError; p.uploadingTarget = null; });
  };
  
  const handleSetPrompt = (prompt: string) => updateActiveProjectState(p => {
    p.prompt = prompt;
    p.isPromptAutoGenerated = false;
  });

  if (!project) return null;

  return (
    <main className="w-full grid grid-cols-1 lg:grid-cols-2 gap-8 pt-4 pb-12 items-start">
        <div className="flex flex-col gap-6 order-1">
            {/* Live Campaign Showcase 1-Click Launch Bar */}
            <div className="glass-card p-4 rounded-3xl border border-purple-500/30 bg-gradient-to-r from-purple-950/40 via-black/40 to-pink-950/20 shadow-xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 animate-in fade-in duration-300">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-purple-600 via-[var(--color-accent)] to-pink-500 flex items-center justify-center text-xl text-white shadow-lg animate-pulse">
                  🔥
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="text-xs sm:text-sm font-black text-white">إطلاق تجربة حملة حية متكاملة (Live Campaign Demo)</h3>
                    <span className="px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 text-[10px] font-black border border-emerald-500/30">
                      Live 1-Click
                    </span>
                  </div>
                  <p className="text-[11px] text-white/50">
                    أمر عربي فخم + بناء الـ 5 طبقات حركياً + توليد معقم + إرسال فوري للـ Social Engine
                  </p>
                </div>
              </div>

              <button
                type="button"
                onClick={handleLaunchLiveCampaignDemo}
                disabled={project.isLoading || project.isAnalyzingScene}
                className="w-full sm:w-auto px-5 py-2.5 rounded-2xl bg-gradient-to-r from-purple-600 via-[var(--color-accent)] to-pink-600 hover:opacity-90 text-white text-xs font-black shadow-xl shadow-purple-900/30 transition-all flex items-center justify-center gap-2 disabled:opacity-50 active:scale-95 whitespace-nowrap"
              >
                {project.isLoading || project.isAnalyzingScene ? (
                  <>
                    <div className="w-3.5 h-3.5 rounded-full border-2 border-white border-t-transparent animate-spin"></div>
                    <span>جاري تشغيل الحملة الحية...</span>
                  </>
                ) : (
                  <>
                    <span>🚀</span>
                    <span>تشغيل الحملة الحية الآن</span>
                  </>
                )}
              </button>
            </div>

            <div className="grid grid-cols-2 gap-4">
                <div className="glass-card p-3 rounded-2xl flex flex-col gap-2 items-center border border-white/5">
                    <h3 className="text-[10px] font-black text-white/40 uppercase tracking-widest">Main Product</h3>
                    <ImageWorkspace
                        id="creator-product-uploader"
                        images={project.productImages}
                        onImagesUpload={handleFileUpload(files => updateActiveProjectState(p => { p.productImages = [...p.productImages, ...files]; }), 'product')}
                        onImageRemove={(idx) => updateActiveProjectState(p => { p.productImages = p.productImages.filter((_, i) => i !== idx); })}
                        isUploading={project.uploadingTarget === 'product'}
                        onImageUpdate={(idx, img) => updateActiveProjectState(p => { p.productImages[idx] = img; })}
                    />
                </div>
                <div className="glass-card p-3 rounded-2xl flex flex-col gap-2 items-center border border-white/5">
                    <h3 className="text-[10px] font-black text-white/40 uppercase tracking-widest">Style Reference</h3>
                    <ImageWorkspace 
                        id="creator-style-uploader"
                        title="Style Image"
                        images={project.styleImages}
                        onImagesUpload={handleFileUpload(files => updateActiveProjectState(p => { p.styleImages = [...p.styleImages, ...files]; p.styleDescription = null; }), 'style')}
                        onImageRemove={(idx) => updateActiveProjectState(p => { p.styleImages = p.styleImages.filter((_, i) => i !== idx); p.styleDescription = null; })}
                        isUploading={project.uploadingTarget === 'style'}
                        onImageUpdate={(idx, img) => updateActiveProjectState(p => { p.styleImages[idx] = img; p.styleDescription = null; })}
                    />
                </div>
            </div>

            {/* HYPER UNIVERSAL SOCIAL ENGINE V1.0 - VISUAL DNA & FACE LOCK CONTROLLER */}
            <div className="p-3.5 rounded-2xl border border-cyan-500/30 bg-gradient-to-r from-cyan-950/40 via-blue-950/20 to-black/60 shadow-xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 animate-fadeIn">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-cyan-400 to-blue-600 flex items-center justify-center text-xl shadow-lg shadow-cyan-500/20 flex-shrink-0 animate-pulse">
                  🧬
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-black text-white">HYPER UNIVERSAL SOCIAL ENGINE V1.0</span>
                    <span className="px-2 py-0.5 rounded-full text-[9px] font-black bg-cyan-500/20 text-cyan-300 border border-cyan-500/40">
                      15 LAYERS • DNA LOCK
                    </span>
                  </div>
                  <p className="text-[10px] text-white/60 mt-0.5">
                    {project.hyperSocialDNA ? (
                      <span className="text-emerald-300 font-bold">
                        ✓ تم استخراج DNA الهوية ({project.hyperSocialDNA.brandAI.industry}) • دستور الـ 3 ألوان: {project.hyperSocialDNA.colorConstitution.primary}
                      </span>
                    ) : (
                      <span>تحليل DNA المراجع تلقائياً • قفل الوجه Face Lock • محرك الكوميديا البيعية واللهجات</span>
                    )}
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2 w-full sm:w-auto">
                <button
                  type="button"
                  onClick={() => handleAnalyzeDNA()}
                  disabled={project.isAnalyzingDNA}
                  className="flex-1 sm:flex-none py-2 px-3 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-black font-black text-xs transition-all shadow-md shadow-cyan-500/25 flex items-center justify-center gap-1.5 active:scale-95 disabled:opacity-50 whitespace-nowrap"
                >
                  {project.isAnalyzingDNA ? (
                    <>
                      <div className="w-3.5 h-3.5 rounded-full border-2 border-black border-t-transparent animate-spin" />
                      <span>جاري فحص الـ DNA...</span>
                    </>
                  ) : (
                    <>
                      <span>🧬</span>
                      <span>{project.hyperSocialDNA ? 'استعراض طبقات الـ DNA الـ 15' : 'تحليل الـ DNA الإعلاني'}</span>
                    </>
                  )}
                </button>

                {project.hyperSocialDNA && (
                  <button
                    type="button"
                    onClick={() => setIsDNAModalOpen(true)}
                    className="py-2 px-3 rounded-xl bg-white/10 hover:bg-white/15 text-cyan-300 border border-cyan-500/30 text-xs font-bold transition-all active:scale-95"
                    title="فتح فاحص الـ DNA"
                  >
                    تفاصيل الـ 15 طبقة ↗
                  </button>
                )}
              </div>
            </div>

            <CustomizationPanel options={project.options} setOptions={(opt) => updateActiveProjectState(p => { p.options = opt; })} />

            <PromptEditor
                prompt={project.prompt}
                setPrompt={handleSetPrompt}
                isAutoGenerated={project.isPromptAutoGenerated}
                onResetPrompt={() => updateActiveProjectState(p => { p.isPromptAutoGenerated = !p.isPromptAutoGenerated; })}
                translatedPrompt={project.translatedPrompt}
                isTranslating={project.isTranslating}
                onUseTranslation={(t) => updateActiveProjectState(p => { p.prompt = t; p.isPromptAutoGenerated = false; p.translatedPrompt = null; })}
                onApplyStockBase={handleApplyStockBase}
                onApplyRimColor={handleApplyRimColor}
                onApplyVisionMode={handleApplyVisionMode}
            />

            {/* Multi-Layer Scene Architecture Trigger & Status */}
            <div className="glass-card p-3 rounded-2xl border border-purple-500/25 bg-gradient-to-r from-purple-950/30 via-black/40 to-black/60 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 shadow-lg">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-xl bg-purple-600/30 border border-purple-500/40 flex items-center justify-center text-lg animate-pulse">
                  🪐
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-black text-white">معمارية المشهد كامل الطبقات</span>
                    <span className="text-[9px] px-2 py-0.5 rounded-full bg-purple-500/20 text-purple-300 font-bold border border-purple-500/30">
                      5 Layers 3D
                    </span>
                  </div>
                  <p className="text-[10px] text-white/50">
                    تحليل الأوامر العربية ومطابقة المراجع المكانية والضوئية قبل التنفيذ
                  </p>
                </div>
              </div>

              <button
                type="button"
                onClick={() => handleAnalyzeScene()}
                disabled={project.isAnalyzingScene || !project.prompt.trim()}
                className="w-full sm:w-auto px-4 py-2 rounded-xl bg-gradient-to-r from-purple-600 to-[var(--color-accent)] hover:from-purple-500 hover:to-[var(--color-accent-dark)] text-white text-xs font-bold shadow-md shadow-purple-900/30 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
              >
                {project.isAnalyzingScene ? (
                  <>
                    <div className="w-3.5 h-3.5 rounded-full border-2 border-white border-t-transparent animate-spin"></div>
                    <span>جاري تحليل الطبقات والمراجع...</span>
                  </>
                ) : (
                  <>
                    <span>🪐</span>
                    <span>{project.sceneAnalysis ? 'إعادة بناء الطبقات' : 'تحليل وبناء المشهد تفاعلياً'}</span>
                  </>
                )}
              </button>
            </div>

            {/* Animated Interactive Multi-Layer Scene Builder (وقبل التنفيذ يكون متحرك كامل الطبقات في الإنشاء) */}
            {project.sceneAnalysis && (
              <SceneLayerBuilder
                sceneAnalysis={project.sceneAnalysis}
                isAnalyzing={project.isAnalyzingScene}
                isGenerating={project.isLoading}
                onApplyAndGenerate={(synthesizedPrompt) => {
                  updateActiveProjectState(p => { p.prompt = synthesizedPrompt; });
                  handleGenerate(synthesizedPrompt);
                }}
                onClose={() => updateActiveProjectState(p => { p.sceneAnalysis = null; })}
                onOpenSocialEngine={() => onOpenSocialEngine && onOpenSocialEngine(null, project.generatedImage, project.prompt)}
              />
            )}

            <button
                onClick={() => handleGenerate()}
                disabled={project.isLoading || !project.prompt || !!project.uploadingTarget}
                className="w-full bg-[var(--color-accent)] hover:bg-[var(--color-accent-dark)] text-white font-black py-5 rounded-2xl text-lg shadow-xl shadow-[var(--color-accent)]/20 transition-all transform active:scale-95 disabled:opacity-50 disabled:transform-none uppercase tracking-widest"
            >
                {project.isLoading ? 'Generating Design...' : 'Generate AI Image'}
            </button>

            {project.error && <div className="bg-red-500/10 border border-red-500/20 text-red-400 px-4 py-3 rounded-xl text-xs font-bold text-center uppercase tracking-tight">{project.error}</div>}
        </div>

        <div className="flex flex-col gap-6 order-2">
             <div className="glass-card rounded-3xl p-6 min-h-[400px] border border-white/5 shadow-2xl flex flex-col gap-4">
                <ResultDisplay 
                    imageFile={project.generatedImage} 
                    isLoading={project.isLoading}
                    onEdit={handleImageEdit}
                    isEditing={project.isEditing}
                    onRequestVideo={(img) => onRequestVideo && onRequestVideo(img, project.prompt, project.hyperSocialDNA)}
                />

                {project.generatedImage && !project.isLoading && onRequestVideo && (
                  <button
                    type="button"
                    onClick={() => onRequestVideo(
                      project.generatedImage, 
                      project.hyperSocialDNA?.comedicSalesVideo?.sceneDirectorialPromptEn || project.prompt, 
                      project.hyperSocialDNA
                    )}
                    className="w-full px-5 py-3 rounded-2xl bg-gradient-to-r from-amber-500 via-orange-600 to-red-600 hover:opacity-95 text-white text-xs font-black shadow-lg shadow-orange-950/30 transition-all flex items-center justify-center gap-2 active:scale-95 animate-in slide-in-from-bottom-1 duration-300"
                  >
                    <span>🎬</span>
                    <span>إنتاج فيديو إعلاني كوميدي سينمائي مع ليبسينج وحركات بيع</span>
                  </button>
                )}

                {project.generatedImage && !project.isLoading && onOpenSocialEngine && (
                  <button
                    type="button"
                    onClick={() => onOpenSocialEngine(null, project.generatedImage, project.prompt)}
                    className="w-full px-5 py-3.5 rounded-2xl bg-gradient-to-r from-pink-600 via-purple-600 to-[var(--color-accent)] hover:opacity-95 text-white text-xs font-black shadow-xl shadow-purple-900/30 transition-all flex items-center justify-center gap-2 active:scale-95 animate-in slide-in-from-bottom-2 duration-300"
                  >
                    <span>📱</span>
                    <span>نشر وجدولة الحملة فوراً في Social Engine (Phase 5)</span>
                    <span>↗️</span>
                  </button>
                )}
             </div>
            <HistoryPanel history={project.history} onSelect={(img) => updateActiveProjectState(p => { p.generatedImage = img; })} />
        </div>

        {/* Visual DNA 15-Layer Inspector & Comedic Video Modal */}
        <VisualDNAInspectorModal
          isOpen={isDNAModalOpen}
          onClose={() => setIsDNAModalOpen(false)}
          dna={project.hyperSocialDNA || null}
          isLoading={project.isAnalyzingDNA}
          onApplyDNA={handleApplyDNA}
          onSendToVideoFlow={(videoPrompt) => {
            if (onRequestVideo) {
              onRequestVideo(project.productImages[0] || null, videoPrompt, project.hyperSocialDNA);
            }
          }}
          onReanalyzeWithDialect={(dialect) => handleAnalyzeDNA(dialect)}
        />
    </main>
  );
};

export default CreatorStudio;
